# Generated by Django 4.2 on 2023-05-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_author_comment_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='comment',
        ),
    ]
